### ISSUE TITLE
can you add support for seconds

### ISSUE THREAD

**Issue by pawaom** [PuffoCyano/Range-Time-Picker-Dialog#1]
can you add support for seconds

with ability to select a range based on hours, minutes, seconds

**Comment by PuffoCyano** [comment]
Hi pawaom. In the next release I will try to add seconds too. I hope to
publish it soon

Il 11 mar 2018 15:21, "pawaom" <notifications@github.com> ha scritto:

**Comment by PuffoCyano** [comment]
Hi Pawaom; I have tried to add support for seconds but it need to change all dialog; so, at the moment I keep it without seconds.
