### ISSUE TITLE
Implementing onDismiss or onCancel method

### ISSUE THREAD

**Issue by DiogoTheCoder** [PuffoCyano/Range-Time-Picker-Dialog#10]
Would like to be able to add code for when the "Cancel" button is pressed

**Comment by PuffoCyano** [comment]
Hi. You should handle onActivityResult; when result is OK it means that
user has pressed Ok button, otherwise user has pressed cancel.

**Comment by DiogoTheCoder** [comment]
Ok will do, thanks

**Comment by kantbinh** [comment]
@PuffoCyano 
It looks like ActivityResult call back only support if show dialog inside Fragment only? How to listen cancel/dismiss call back if i show dialog from Activity?
