### ISSUE TITLE
Modification for minimum time selection

### ISSUE THREAD

**Issue by mrkamiali** [PuffoCyano/Range-Time-Picker-Dialog#11]
I want to check if a difference between two times is less then 30m, toast to User selected time must be greater then 30min, can you please make it do this task asap?
This task is actually a range checker,

**Comment by mrkamiali** [comment]
I have implemented it and created a pull request to merge, please check hope you like it.

**Comment by PuffoCyano** [comment]
I have merged ;) thanks

**Comment by mrkamiali** [comment]
Thank you, please update the library so I can use it in to my project.
