### ISSUE TITLE
Add support for SupportFragments and possibility of disabling minutes.

### ISSUE THREAD

**Issue by stshelton** [PuffoCyano/Range-Time-Picker-Dialog#2]
Currently using support fragments in my project and the `dialog.setTargetFragment()` is expecting a fragment. Anyway of using support fragments? Also allowing minutes to be disabled would be a cool feature.

**Comment by PuffoCyano** [comment]
Hi, thanks for feedback. Have you use android.support.v4.fragment? In this
case, for now, I don't know how resolve your problem but with the next
release I will try to support it too. For the possibility to disabling
minutes, in the next release I will add it. Thanks and have a good day

Il mer 28 mar 2018, 01:37 stshelton <notifications@github.com> ha scritto:

**Comment by cheetahdeliverys** [comment]
hi, I have the same problem.

**Comment by PuffoCyano** [comment]
Hi guys. In the last release I have added the ability to disable minutes. Try it ;)

**Comment by iC00kScripts** [comment]
`dialog.setTargetFragment()` is still expecting a fragment not a support fragment. Apart from this, this library is quite awesome. Sad I can't use at the moment.

**Comment by PuffoCyano** [comment]
Hi. Unfortunately at the moment I can't implement supportFragment. Maybe in
the future I will support it 🤔 However thank you very much for your
feedback
