### ISSUE TITLE
No virtual method addOnTabSelectedListener

### ISSUE THREAD

**Issue by farislivemaker** [PuffoCyano/Range-Time-Picker-Dialog#6]
I don't know why this happens initially it works fine, But all the sudden I came up with this error.

` Process: com.xxx.yyy.zzz, PID: 27215
    java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.xxx.yyy.tpvisitor-2/base.apk:classes4.dex)
        at com.mcsoft.timerangepickerdialog.RangeTimePickerDialog$1.onShow(RangeTimePickerDialog.java:147)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1352)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5728)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

This is my build. gradle module-app dependencies

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.google.code.gson:gson:2.6.1'
    implementation 'com.github.PuffoCyano:Range-Time-Picker-Dialog:v1.6'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by kantbinh** [comment]
I have the same issue, do you find why ?

**Comment by farislivemaker** [comment]
yeah, This library is using support library version 27.x.x and my app using 28.x.x. Just download and include this library as a module and change the support library version same as your app version.

**Comment by PuffoCyano** [comment]
In the last release I have update sdk version to 28.x.x

**Comment by kantbinh** [comment]
@PuffoCyano,

So, the newest version is 1.7. Please update ReadMe

**Comment by PuffoCyano** [comment]
No the newest version is 1.6 and I have updated it introducing the ability to enable or disable minutes and also updating SDK 🤔

**Comment by tahercoolguy** [comment]
Getting same problem . Due to library mis versions

**Comment by kantbinh** [comment]
Hello @PuffoCyano .
The issue still happened on your newest version when use Android SDK 28.0.0. Can you please make an update ? Thank you

**Comment by kantbinh** [comment]
hello @PuffoCyano . Can you please make a update for this library ?

**Comment by PuffoCyano** [comment]
Hi. Yes, I update it soon.

Il giorno dom 25 nov 2018, 08:22 Nguyen Cong Binh <notifications@github.com>
ha scritto:

**Comment by PuffoCyano** [comment]
@nguyencongbinh I have release a new release (1.7) that resolve your problems. Try it and keep me udated. Thanks ;)

**Comment by kantbinh** [comment]
Thank you so much @PuffoCyano. I just updated and it worked well. Thank for your awesome libs.

**Comment by PuffoCyano** [comment]
Thank you for feedbacks 😎

Il giorno dom 25 nov 2018, 12:19 Nguyen Cong Binh <notifications@github.com>
ha scritto:
