### ISSUE TITLE
How to set initial clock value, set clock text size, set initial opened tab, set tab icon, and use keyboard input as default?

### ISSUE THREAD

**Issue by txufiknr** [PuffoCyano/Range-Time-Picker-Dialog#7]
How to set initial clock value, set clock text size, set initial opened tab, set tab icon with my own drawables, and use keyboard input as default? And when I use snippet on my activity, `fragmentManager` is deprecated, but when I changed it to `supportFragmentManager` parameter is not valid. How to fix it? Thank you so much.

**Comment by PuffoCyano** [comment]
Hi @topex-psy, your tips are interesting. In the next ours I will implement them. However, regarding to fragmentManager, at the moment it is necessary and I can't use supportFragmentManager.

**Comment by PuffoCyano** [comment]
Hi @topex-psy it's available a new release; try it ;)

**Comment by txufiknr** [comment]
I've tried the update. Awesome! But seems the option to set the font size of the HH:mm clock is still not available. It's too small on my device unlike the screenshot in readme.

**Comment by PuffoCyano** [comment]
Hi @topex-psy unfortunately it difficult to set font size; maybe, in the future, I will try to implement it.

**Comment by txufiknr** [comment]
I see. Thank you so much.
